### ISSUE TITLE
JBrowse extensions

### ISSUE THREAD

**Issue by Slugger70** [bxlab/galaxy-hackathon#10]
E Rasche's (@erasche) JBrowse tool is pretty awesome.. The idea here is to add some functionality to the tool.
- Add the indexed reference genomes to @erasche's JBrowse tool
- Add some minor display options
  - gff default label type (gene, product etc)
  - Same for vcf
- Default start display options and location

Should be a small job.

**Comment by hexylena** [comment]
xref https://github.com/galaxyproject/tools-iuc/issues/508

**Comment by nathandunn** [comment]
👍

**Comment by Slugger70** [comment]
PR submitted to galaxyproject/tools-iuc
