### ISSUE TITLE
Galaxy tools/conda, works in progress and to be done

### ISSUE THREAD

**Issue by dpryan79** [bxlab/galaxy-hackathon#23]
Please add any tools that you're adding to conda below. Feel free to modify this comment to add things.
- [x] hmmer3 galaxyproject/tools-iuc/pull/841
- [x] deseq2 galaxyproject/tools-iuc/pull/842
- [x] qiime galaxyproject/tools-iuc/pull/431
- [x] seqtk galaxyproject/tools-iuc/pull/843
- [x] prokka
- [x] stringTie
- [x] HTSeq
- [ ] RGI tool
- [x] bcftools
- [x] xpath galaxyproject/tools-iuc/pull/847
- [x] transdecoder galaxyproject/tools-iuc/pull/846
- [x] raxml galaxyproject/tools-iuc/pull/855
- [x] art galaxyproject/tools-iuc/pull/856

**Comment by dannon** [comment]
bcftools

**Comment by dpryan79** [comment]
It looks like bcftools-1.2 and 1.3 should both be available in conda already.

**Comment by lecorguille** [comment]
WIP on DESeq2 : waiting for Travis test

**Comment by lecorguille** [comment]
WIP on trandecoder : waiting for Travis test

**Comment by lecorguille** [comment]
WIP on htseq

**Comment by dpryan79** [comment]
@lecorguille: HTSeq is already finished.

**Comment by bgruening** [comment]
@davebx are you still working on the wrapper side of stringtie? There is now a conda package.

**Comment by lecorguille** [comment]
Transdecoder is done

**Comment by dpryan79** [comment]
I assume this can be closed after 2 years :)
